[project]
name = "tg"
version = "1.0.0"
requires-python = ">=3.10,<3.15"
dependencies = [
    "libdev==0.100",
    "fastapi==0.126.0",
    "uvicorn==0.38.0",
    "aiogram==3.23.0",
]

[tool.uv]
dev-dependencies = []
